build-stable:
	    docker build -t waikato/weka:latest -f stable.Dockerfile .
build-devel:
	    docker build -t waikato/weka:devel -f devel.Dockerfile .
push-latest:
	    docker push waikato/weka:latest
push-devel:
	    docker push waikato/weka:devel
